-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-1');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with 4;

insert into t_robot (serialNr, robot_name, job, image, city) values ('e5ba7533-eb55-4197-bf4d-7fe39ca4cd62', 'Drospirenone/ethinyl estradiol/levomefolate calcium and levomefolate calcium', 'Senior Sales Associate', 'https://robohash.org/dolorumetquas.png?size=50x50&set=set1', 'Köln');
insert into t_robot (serialNr, robot_name, job, image, city) values ('b58d50c2-dced-473e-b073-4474e18d34e2', 'Phentermine Hydrochloride', 'Internal Auditor', 'https://robohash.org/etautquibusdam.png?size=50x50&set=set1', 'Pindobaçu');
insert into t_robot (serialNr, robot_name, job, image, city) values ('08030256-82b1-493d-9fc0-020ca333304b', 'Metoprolol Tartrate', 'Editor', 'https://robohash.org/minusetaccusantium.png?size=50x50&set=set1', 'Sendai-shi');
insert into t_robot (serialNr, robot_name, job, image, city) values ('ef6ce38f-6edb-436a-93e5-9664b3c505fb', 'BENZOYL PEROXIDE', 'Business Systems Development Analyst', 'https://robohash.org/velitarchitectoet.png?size=50x50&set=set1', 'Oslo');
insert into t_robot (serialNr, robot_name, job, image, city) values ('b5a5ce17-cbee-43a8-b4fe-ab0c0ea6217a', 'Povidone-Iodine', 'Physical Therapy Assistant', 'https://robohash.org/utliberoamet.png?size=50x50&set=set1', 'Casilda');
insert into t_robot (serialNr, robot_name, job, image, city) values ('84de124a-64de-41e9-8774-0f978f7d6371', 'Jacobaea Maritima, Calcium Fluoride, Conium Maculatum Flowering Top, Euphrasia Stricta, Gelsemium Sempervirens Root, Sodium Chloride, Ruta Graveolens Flowering Top', 'Nurse', 'https://robohash.org/accusantiumrerumid.png?size=50x50&set=set1', 'Kroya');
insert into t_robot (serialNr, robot_name, job, image, city) values ('64d21e0f-185f-481f-b7be-31d5892ef1c9', 'Ampicillin and Sulbactam', 'Nurse', 'https://robohash.org/quasaliasrepudiandae.png?size=50x50&set=set1', 'Antes');
insert into t_robot (serialNr, robot_name, job, image, city) values ('9db0276a-98f1-432b-8497-0f7acb54a355', 'PENTOXIFYLLINE', 'Engineer III', 'https://robohash.org/idpariaturest.png?size=50x50&set=set1', 'Guazhou');
insert into t_robot (serialNr, robot_name, job, image, city) values ('05ef6d7a-5f8a-434e-aa24-0ae9b941d314', 'THYROID', 'Data Coordinator', 'https://robohash.org/fugiatiurequo.png?size=50x50&set=set1', 'Vigan');
insert into t_robot (serialNr, robot_name, job, image, city) values ('e8bfbccf-ee89-4c6a-b2e1-836e289c8dbb', 'Naproxen Sodium', 'Librarian', 'https://robohash.org/hicarchitectoeos.png?size=50x50&set=set1', 'Mostek');
insert into t_robot (serialNr, robot_name, job, image, city) values ('ca8c267a-260c-4327-99b9-dafca5a8f6a8', 'nifedipine', 'Teacher', 'https://robohash.org/repudiandaedolorenam.png?size=50x50&set=set1', 'Nový Hrozenkov');
insert into t_robot (serialNr, robot_name, job, image, city) values ('b68016d9-3112-4d3e-bd83-ee5f21fb7e26', 'AVOBENZONE, OCTINOXATE, OCTOCRYLENE, and OXYBENZONE', 'Help Desk Technician', 'https://robohash.org/culpaeosvero.png?size=50x50&set=set1', 'Mateus Leme');
insert into t_robot (serialNr, robot_name, job, image, city) values ('d8bec22b-e320-4b05-bcfc-f9065d3eda4d', 'Glycopyrrolate', 'GIS Technical Architect', 'https://robohash.org/rerumquisquamatque.png?size=50x50&set=set1', 'Thị Trấn Hà Trung');
insert into t_robot (serialNr, robot_name, job, image, city) values ('1ab26377-10dd-4efc-8f2e-eca6c0e84184', 'Hydrogen Peroxide', 'Help Desk Operator', 'https://robohash.org/nonnatusdoloribus.png?size=50x50&set=set1', 'Nsanje');
insert into t_robot (serialNr, robot_name, job, image, city) values ('096831be-8d60-4394-9118-6c16c28dc932', 'Ethyl Alcohol', 'Compensation Analyst', 'https://robohash.org/nesciuntperspiciatisofficia.png?size=50x50&set=set1', 'Castilla');
insert into t_robot (serialNr, robot_name, job, image, city) values ('f42e26aa-2715-43b1-b72c-9f026f323cc3', 'External Analgesic Plaster for Removal of Corns and Calluses', 'Human Resources Manager', 'https://robohash.org/optionequeconsequuntur.png?size=50x50&set=set1', 'Malway');
insert into t_robot (serialNr, robot_name, job, image, city) values ('23a2a0d4-8ec5-4ac2-9406-f1ac28cd69c3', 'tamsulosin hydrochloride', 'Pharmacist', 'https://robohash.org/corporisetut.png?size=50x50&set=set1', 'Gal’bshtadt');
insert into t_robot (serialNr, robot_name, job, image, city) values ('e968f4d2-4932-4552-bc4a-ba3415a73898', 'CITALOPRAM HYDROBROMIDE', 'Pharmacist', 'https://robohash.org/consequatursequimagni.png?size=50x50&set=set1', 'Vannes');
insert into t_robot (serialNr, robot_name, job, image, city) values ('21f3c9a8-f5f3-4dec-8b92-e77376994d74', 'Camphor, Menthol, Methyl Salicylate', 'Budget/Accounting Analyst III', 'https://robohash.org/idquoea.png?size=50x50&set=set1', 'Manosque');
insert into t_robot (serialNr, robot_name, job, image, city) values ('5d97360b-2341-4a13-b3e8-350b972e4238', 'bacitracin, neomycin, polymyxin B', 'Civil Engineer', 'https://robohash.org/evenietvoluptatumconsequatur.png?size=50x50&set=set1', 'Vidče');